"""empty message

Revision ID: 8fdbb9a7c7c9
Revises: 
Create Date: 2024-08-13 11:03:01.619097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fdbb9a7c7c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('is_default_area', sa.Boolean(), nullable=False),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('updated_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_status', sa.String(length=255), nullable=False),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('updated_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_user_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_status', sa.String(length=255), nullable=False),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('updated_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_address', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_name_kana', sa.String(length=255), nullable=False),
    sa.Column('default_area_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('user_status_id', sa.Integer(), nullable=False),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('updated_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['m_area.id'], ),
    sa.ForeignKeyConstraint(['attendance_id'], ['m_attendance.id'], ),
    sa.ForeignKeyConstraint(['user_status_id'], ['m_user_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_user')
    op.drop_table('m_user_status')
    op.drop_table('m_attendance')
    op.drop_table('m_area')
    # ### end Alembic commands ###
